### PR TITLE
Add RawMessage, like json.RawMessage, but implements proto.{Marshaler,Unmarshaler}.

### PR DESCRIPTION
**Pull request by dmitshur**
This is needed to fix a regression caused by https://github.com/sourcegraph/srclib/pull/177, since `json.RawMessage` (of `encoding/json`) does not implement `proto.Marshaler` and `proto.Unmarshaler`.

### CODE REVIEW

File: rawmessage.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+func (m *RawMessage) MarshalJSON() ([]byte, error) {
+	return *m, nil
+}
+
+// UnmarshalJSON sets *m to a copy of data.
+func (m *RawMessage) UnmarshalJSON(data []byte) error {
+	if m == nil {
+		return errors.New("pbtypes.RawMessage: UnmarshalJSON on nil pointer")
+	}
+	*m = append((*m)[0:0], data...)
```
Comment (beyang) [inline rawmessage.go:20]: this is an ingenious little snippet of code
